chore: cache the hermeto cache
Signed-off-by: Frank Kong <frkong@redhat.com>

rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED

diff --git a/.github/actions/docker-build/action.yaml b/.github/actions/docker-build/action.yaml
--- a/.github/actions/docker-build/action.yaml
+++ b/.github/actions/docker-build/action.yaml
@@ -75,55 +75,69 @@ runs:
         echo "LOCAL_CACHE_DIR=./hermeto-cache/$(basename "$COMPONENT_DIR")" >> $GITHUB_ENV
         echo "COMPONENT_ABS_DIR=${GITHUB_WORKSPACE}/${COMPONENT_DIR}" >> $GITHUB_ENV
 
+    - name: Restore hermeto cache
+      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
+      with:
+        path: ${{ env.LOCAL_CACHE_DIR }}
+        key: hermeto-cache-${{ inputs.platform }}-${{ hashFiles('yarn.lock', 'dynamic-plugins/yarn.lock', 'rpms.lock.yaml', 'python/requirements.in', 'python/requirements-build.in') }}
+    
     - name: Cache dependencies with hermeto
       shell: bash
       run: |        
         set -ex
-
-        echo "::group::Creating local cache directory"
-        mkdir -p ${{ env.LOCAL_CACHE_DIR }} || echo "Failed to create local cache directory"
-        echo "::endgroup::"
-        
-        echo "::group::Fetching dependencies with hermeto"
-        # Build hermeto cache for rpm, yarn, and pip
-        podman run --rm -v "$PWD:/source:z" -v "$LOCAL_CACHE_DIR:/cachi2:z" -w /source "$HERMETO_IMAGE" \
-          --log-level DEBUG \
-          fetch-deps --dev-package-managers \
-          --source . \
-          --output /cachi2/output \
-          '[{"type": "rpm", "path": "."}, {"type": "yarn","path": "."}, {"type": "yarn","path": "./dynamic-plugins"}, {"type": "pip","path": "./python", "allow_binary": "false"}]'  || echo "Fetch-deps failed"
-        echo "::endgroup::"
-        
-        if [ -d ${{ env.LOCAL_CACHE_DIR }}/output ]; then
-          echo "::group::Generating environment file"
-          
-          # Generate environment file
-          podman run --rm -v "$PWD:/source:z" -v "$LOCAL_CACHE_DIR:/cachi2:z" -w /source "$HERMETO_IMAGE" \
-                      --log-level DEBUG \
-                      generate-env --format env \
-                      --output /cachi2/cachi2.env /cachi2/output
+        if [ -d ${{ env.LOCAL_CACHE_DIR }} ]; then
+          echo "::group::Restoring cached hermeto cache"
           echo "::endgroup::"
-          
         else
-          echo "No output directory found, skipping generate-env"
-          exit 1
-        fi
+          echo "::group::Creating new hermeto cache"
+          mkdir -p ${{ env.LOCAL_CACHE_DIR }} || echo "Failed to create local cache directory"
+          echo "::endgroup::"
 
-        if [ -d ${{ env.LOCAL_CACHE_DIR }}/output ]; then
-          echo "::group::Injecting files"
-          
+          echo "::group::Fetching dependencies with hermeto"
+          # Build hermeto cache for rpm, yarn, and pip
           podman run --rm -v "$PWD:/source:z" -v "$LOCAL_CACHE_DIR:/cachi2:z" -w /source "$HERMETO_IMAGE" \
             --log-level DEBUG \
-            inject-files /cachi2/output || echo "Inject-files failed"
+            fetch-deps --dev-package-managers \
+            --source . \
+            --output /cachi2/output \
+            '[{"type": "rpm", "path": "."}, {"type": "yarn","path": "."}, {"type": "yarn","path": "./dynamic-plugins"}, {"type": "pip","path": "./python", "allow_binary": "false"}]'  || echo "Fetch-deps failed"
           echo "::endgroup::"
+          
+          if [ -d ${{ env.LOCAL_CACHE_DIR }}/output ]; then
+            echo "::group::Generating environment file"
+            
+            # Generate environment file
+            podman run --rm -v "$PWD:/source:z" -v "$LOCAL_CACHE_DIR:/cachi2:z" -w /source "$HERMETO_IMAGE" \
+                        --log-level DEBUG \
+                        generate-env --format env \
+                        --output /cachi2/cachi2.env /cachi2/output
+            echo "::endgroup::"
+            
+          else
+            echo "No output directory found, skipping generate-env"
+            exit 1
+          fi
 
-        else
-          echo "No output directory found, skipping inject-files"
-          exit 1
+          if [ -d ${{ env.LOCAL_CACHE_DIR }}/output ]; then
+            echo "::group::Injecting files"
+            
+            podman run --rm -v "$PWD:/source:z" -v "$LOCAL_CACHE_DIR:/cachi2:z" -w /source "$HERMETO_IMAGE" \
+              --log-level DEBUG \
+              inject-files /cachi2/output || echo "Inject-files failed"
+            echo "::endgroup::"
+
+          else
+            echo "No output directory found, skipping inject-files"
+            exit 1
+          fi
         fi
-
         echo LOCAL_CACHE_DIR_REALPATH=$(realpath "${{ env.LOCAL_CACHE_DIR }}") >> $GITHUB_ENV
-
+    - name: Save hermeto cache
+      uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
+      with:
+        path: ${{ env.LOCAL_CACHE_DIR }}
+        key: hermeto-cache-${{ inputs.platform }}-${{ hashFiles('yarn.lock', 'dynamic-plugins/yarn.lock', 'rpms.lock.yaml', 'python/requirements.in', 'python/requirements-build.in') }}
+    
     - name: "Fix Cache Ownership for Non-Root Buildah"
       shell: bash
       run: |
